### ISSUE TITLE
Experimental semicolon auto insertion breaks in non-editable buffers

### ISSUE THREAD

**Issue by FuzzOli87** [lfilho/cosco.vim#12]
Hello,

Trying out the auto insertion and so far it was working ok. However, it does break when it tries to modify something that isn't modifiable such as a Unite buffer.

**Comment by lfilho** [comment]
Hey @FuzzOli87 thanks... @ammarnajjar could you maybe check that for us, please?

One possible quick fix is to defined the autocommand for that mapping to only run in specific file types (actual language files and only that)

**Comment by ammarnajjar** [comment]
When the buffer is read-only (RO) the following message appears:
```
E21: Cannot make changes, 'modifiable' is off
```
what does "breaks" mean? please provide more info.

Until the main plugin (actual insertion) is mature enough to recognize where it should insert, and where not to, auto-insertion will keep do undesired actions. The user should be aware.

*Personal opinion: "auto-action" should not be clever but the "action" itself. "auto-action" only keeps triggering the "action".*

**Comment by FuzzOli87** [comment]
@ammarnajjar It means that it throws errors like the one you posted. Inserts where it shouldn't.

**Comment by lfilho** [comment]
Just pushed a commit that should fix this. Try it out
