### ISSUE TITLE
Semicolons added to methods if braces are opened on the next line

### ISSUE THREAD

**Issue by KroniK907** [lfilho/cosco.vim#14]
I generally code using the format:
```
public function name()
{
    something here;
}
```
When I use this formatting along with the auto add semicolons function it likes to add semicolons to the end of my function declaration like so:
```
public function name();
{
    something here;
}
```
Is there a way that we could have it check the next line for an opening brace and not add a semicolon if the next line starts with an opening brace?

**Comment by lfilho** [comment]
I have just pushed a commit that tried to address this.
Please test it (the most extensively you can) and let me know if it seems to be working fine

**Comment by KroniK907** [comment]
This seems to be working as expected. Thank you!
