### ISSUE TITLE
New "Undefined variable" error when invoking on Neovim

### ISSUE THREAD

**Issue by bugeats** [lfilho/cosco.vim#17]
Hey there. Long time user of this wonderful plugin. After a recent update, I started getting the below error.

```
Error detected while processing function cosco#commaOrSemiColon[31]..<SNR>194_hasUnactionableLines:
line    2:
E121: Undefined variable: g:cosco_ignore_comment_lines
E15: Invalid expression: (g:cosco_ignore_comment_lines == 1)
```

`NVIM v0.2.1-596-g5a0acd09c`

Config file here:
  https://github.com/bugeats/dotfiles/blob/master/src/config/nvim/init.vim

**Comment by bugeats** [comment]
Fixed by explicitly adding `let g:cosco_ignore_comment_lines = 1` directly in my config.

**Comment by lfilho** [comment]
Thanks, @bugeats I should have added a guard against that var being undefined, of course... Will do so soon. Thanks for reporting it.f

**Comment by bugeats** [comment]
Why would you close the ticket if you haven't fixed the bug?

**Comment by lfilho** [comment]
![image](https://user-images.githubusercontent.com/282756/28636486-92bce6c6-723e-11e7-9e89-642d019d1c97.png)

Please notice that this was closed by a commit, which contains (hopefully) the fix for it 😉. Don't throw your stones too soon. 😊

**Comment by bugeats** [comment]
Yep, my bad. 

I just pulled your changes locally and can confirm the fix. Thanks.
