### ISSUE TITLE
print "test"; # here's a comment (adds ; here)

### ISSUE THREAD

**Issue by dezza** [lfilho/cosco.vim#18]
Hello. Just wanna report this small issue which adds a semicolon on lines even if preceded by a hash `#`

```perl
print "test"; # here's a comment;
#                               ^ adds a semicolon even if preceded by a #
```

```perl
if ( $whatever ) {;
#                 ^ same is true for constructs
```

**Comment by lfilho** [comment]
Have you tried the `g:cosco_ignore_comment_lines` option?

Also, second scenario should work: https://github.com/lfilho/cosco.vim/blob/master/autoload/cosco.vim#L55-L58

Could you please double check and help debug otherwise?

**Comment by lfilho** [comment]
Closing as per lack of correspondence from original poster.
