### ISSUE TITLE
colon support, in addition to comma or semicolon

### ISSUE THREAD

**Issue by damnskippy** [lfilho/cosco.vim#19]
Question, or an enhancement request: 
Just wondering if you may have considered adding "colon" in addition to comma or semicolon (I'm asking with python in mind).
Is that not feasible?
Thanks.

**Comment by lfilho** [comment]
Currently is not supported and it would be a fair amount of work to make it work properly. I don't have time for this implementation so I encourage you to try and create a PR for that.

Thanks for your suggestion though.
