### ISSUE TITLE
Allow users to ignore semicolon insertion based on a regex pattern

### ISSUE THREAD

**Issue by viniarck** [lfilho/cosco.vim#21]
Hi Luiz, 

I code in C++ so, I'm using cosco.vim to auto insert semicolons. It turns out that when I inserted an include statement, such as `#include <iostream>`, then cosco.vim auto inserted the semicolon, which is undesirable. 

I believe if you could allow the users to have a variable to ignore some patterns based on regex that'd be great to workaround such minor exceptions. What do you say? I patched the code, https://github.com/viniarck/cosco.vim/commit/a8453012257aa718b67ceb3de460adba9c401ecf, and I'm using this variable to ignore C/C++ include statements:

```
let g:cosco_ignore_pattern="^#"
```

Let me know if I should open a PR for this or if you have an ideia for a better or more robust approach to ignore patterns. Once again, thanks for cosco.vim, it's really awesome!

**Comment by viniarck** [comment]
Sure thing. I'll look into it, @lfilho, I think a dictionary would be the way to go to allow an ignore pattern per filetype.

**Comment by lfilho** [comment]
Closing as per https://github.com/lfilho/cosco.vim/pull/22. Thanks again!
