### ISSUE TITLE
Doesn't recognize common comment blocks.

### ISSUE THREAD

**Issue by jeffschwartz** [lfilho/cosco.vim#28]
It is common (in JavaScript, for instance) to have comment block such as the following:

`Often used for jsdoc`
```javascript
/**;
 * Represents a book.;
 * @constructor;
 */;
function Book(title, author) {
}
```

`Ordinary comment block` 
```
/*;
* This is a comment.;
*/;
```

_However, Cosco doesn't recognize them as legitimate comment blocks ._

My OS: Mac Monterey

My vim configuration:

```vim
""
" Plugin: Cosco
" Colon and Semicolon insertion
""

augroup cosco
    autocmd FileType javascript,css,json nmap <silent> <Leader>; <Plug>(cosco-commaOrSemiColon)
    autocmd FileType javascript,css,json imap <silent> <Leader>; <c-o><Plug>(cosco-commaOrSemiColon)
augroup END

let g:cosco_ignore_comment_lines = 1     " Default : 0
let g:auto_comma_or_semicolon = 1     " Default : 0
" let g:cosco_filetype_whitelist = ['php', 'javascript']
let g:cosco_filetype_blacklist = ['vim', 'bash', 'lua']
```

**Comment by jeffschwartz** [comment]
I am not fluent in vim script but I would guess that the issue might be related to this code:

```vim
function! s:hasUnactionableLines()
    " Ignores comment lines, if global option is configured
    if (g:cosco_ignore_comment_lines == 1)
        let l:isComment = synIDattr(synID(line("."),col("."),1),"name") =~ '\ccomment'
        if l:isComment
            return 1
        endif
    endif
   ...
```

I added the following to my nvim configuration:

```vim
nnoremap <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```
And the results from running it in both of the comment blocks in my op are:

`hi<javaScriptComment> trans<javaScriptComment> lo<Comment>`

**Comment by lfilho** [comment]
Hey Jeff, thanks for reporting this.

I believe I have found the problem. As you can see in the snippet you pasted above, we're expecting a string `"comment"`, but, at least in my setup it's returning `"jsComment"` (note it's already different than yours above). This was not the case when I first wrote the plugin. 

I'm hesitant in adding a `jsComment`, `javaScriptComment` to the condition as it would bloat the generic code with something specific to Js...

Can you try fiddling with that match in there, maybe `\c*comment` would do the trick... I'm on vacation right now so hard for me to test.

PS: Since Javascript is your use case, have you considered using eslint + prettier for taking care of colon/semi-colon for you? That combo works better than my plugin for javascript, plus all the other features they would give you :)

**Comment by jeffschwartz** [comment]
@lfilho thank you for your really rapid response. Greatly appreciated. Though I'm not fluent in vim script I'll gladly take a look and if I can get it to work generically as you suggested then I will issue a pull request. Have a great vacation :)

**Comment by jeffschwartz** [comment]
@lfilho I have filed an issue with Neovim. You can view it [here](https://github.com/neovim/neovim/issues/17746). Your code is correct and would work but synIDattr(synID(line("."),col("."),1) randomly repots an erroneous syntax ID. I am closing out this issue for now but please allow further commenting so that I can report back when the issue is resolved. Thank you for you assistance. Greatly appreciated.

**Comment by jeffschwartz** [comment]
Oh,  as for using prettier, well I lean towards plugins that have a narrow focus, though I have to admit I would be totally lost if I wasn't using eslint lol. Have a great day :)

**Comment by lfilho** [comment]
Ahhh sorry! Thanks for doing that! 

Will definitely leave it in for comments, don't worry. 

I commented in the issue in there, I suspect it had to do with syntax plugins rather than (n)vim itself...

**Comment by jeffschwartz** [comment]
@lfilho thanks for the suggestion. It yielded the same result. See image below.

<img width="508" alt="Screen Shot 2022-03-16 at 1 48 56 PM" src="https://user-images.githubusercontent.com/271288/158655023-0e4622d3-8f9a-4c04-a2e9-5d01580ccaf9.png">

I also observed it returning an erroneous syntax ID for block comments that didn't have any blank lines, meaning they actually contained text with in the comment block. It happens randomly. Perhaps this is a bug inherited from Vim itself. I don't have vim installed, do you? If you do and you feel like sherlocking you can use the below init file to trigger the report.

```vim
nnoremap <F10> :echo "hi<" . synIDattr(synID(line("."),col("."),1),"name") . '> trans<'
\ . synIDattr(synID(line("."),col("."),0),"name") . "> lo<"
\ . synIDattr(synIDtrans(synID(line("."),col("."),1)),"name") . ">"<CR>
```

**Comment by jeffschwartz** [comment]
No problem. It's my nature to want to fix things lol 😹.
