### ISSUE TITLE
Make the action repeatable with `.`

### ISSUE THREAD

**Issue by roryokane** [lfilho/cosco.vim#7]
When I have `:call cosco#commaOrSemiColon()<CR>` bound to a mapping like `<Leader>;`, I might want to repeat that command with `.`. For example, I might want to do `<Leader>;j.` to add semicolons to two consecutive lines. Currently, the plugin does not support that – `.` just repeats the last command I did before calling cosco.

You can use tpope’s [repeat.vim](https://github.com/tpope/vim-repeat) to easily add `.` support to your plugin as long as the user has repeat.vim installed.

**Comment by lfilho** [comment]
I'll take a look at it when I have more time... Thanks for the suggestion.
PR are always welcome :)

**Comment by lfilho** [comment]
Just merged #11 that implements the repeat feature. Give it a go! :)
